### ISSUE TITLE
Request for Access to Dataset for Reproducing Results in "FinerFact" Paper

### ISSUE THREAD

**Issue by zhangweijian97** [Ahren09/FinerFact#4]
Dear Dr. Jin and Dr. Liao,

I hope this email finds you well. My name is Zhang Weijian, and I am a Ph.D. candidate in Computer Science at the University of Macau, currently conducting research on fake news detection.

I recently came across your paper titled "Towards Fine-Grained Reasoning for Fake News Detection" on arXiv (https://arxiv.org/abs/2110.15064) and found it highly relevant and insightful for my research. I am particularly interested in reproducing the results presented in your paper to further understand and build upon your work.

I have accessed the code provided in your GitHub repository (https://github.com/Ahren09/FinerFact). However, I noticed that the dataset required to run the experiments is not included. Given the recent restrictions imposed by Twitter on API access, I am unable to independently download the necessary Twitter data to recreate the dataset.

Therefore, I am writing to kindly request if you could share the dataset used in your study. Access to this dataset would be invaluable for my research, allowing me to accurately replicate your findings and contribute to the ongoing research in this field. I assure you that any data shared will be used strictly for academic purposes and in accordance with data privacy and ethical guidelines.

Thank you very much for your time and consideration. I look forward to your positive response.

Best regards,

Zhang Weijian  
Ph.D. Candidate, Computer Science  
University of Macau  
yc07419@um.edu.mo

**Comment by Ahren09** [comment]
Hi Weijian,

Sorry about the late response. The dataset is available at [Huggingface](https://huggingface.co/datasets/Ahren09/FakeNewsNet). It seems that the previous link for the data has expired, so I re-uploaded it to an alternative location

Cheers

**Comment by shubhamgpt007** [comment]
@zhangweijian97, are you able to run this code? Can you please help in creating the graph?

Thanks for the help.
